#! /usr/bin/env fish

argparse 'i/instruction=' 'f/file=' -- $argv

set token (security find-generic-password -a $USER -s OpenAI -w)

if test $_flag_file
    set input (cat $_flag_file | string collect -N)
else
    read -z input
end

set request (jq -n -c --arg input "$input" --arg instruction "$_flag_instruction" '.model = "code-davinci-edit-001" | .input = $input | .instruction = $instruction')

curl -s -X POST https://api.openai.com/v1/edits \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $token" \
    -d "$request" | jq -r '.choices[0].text'
